# vim: ft=yaml.ansible
---
- name: Install dependencies via apt
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: present
  become_user: root
  vars:
    pkgs:
      - acl
      - automake
      - build-essential
      - clang
      - cmake
      - git
      - libgmp-dev
      - libntl-dev
      - libsodium-dev
      - libssl-dev
      - libtool
      - m4
      - python3
      - texinfo
      - yasm

- name: Clone MP-SPDZ
  ansible.builtin.git:
    repo: https://github.com/data61/MP-SPDZ
    dest: "{{ mp_spdz.dir }}"
    version: "{{ mp_spdz.version }}"
    clone: true
    update: false
    recursive: true
    single_branch: true
    depth: 1

- name: Create CONFIG.mine
  ansible.builtin.copy:
    dest: "{{ mp_spdz.dir }}/CONFIG.mine"
    owner: "{{ username }}"
    mode: u=rw,g=r,o=r
    content: |
      ARCH = -mtune=native -msse4.1 -msse4.2 -maes -mpclmul -mavx -mavx2 -mbmi2 -madx

- name: Build MP-SPDZ
  community.general.make:
    chdir: "{{ mp_spdz.dir }}"
    jobs: "{{ ansible_processor_nproc }}"
    target: "{{ item }}"
  loop:
    - boost
    - libote
    - semi2k-party.x
