# vim: ft=yaml.ansible
---
- name: Provision MPC players
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Create user {{ username }}
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ secrets.user_password | ansible.builtin.password_hash('sha512') }}"
        update_password: on_create
        groups:
          - sudo
        state: present

    - name: Add public SSH key to user {{ username }}
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_key }}"
        exclusive: true

    - name: Import role mp_spdz
      ansible.builtin.import_role:
        name: mp_spdz
      become_user: "{{ username }}"
